### ISSUE TITLE
Please Add Build and Dependency Instructions For wAx Source Code

### ISSUE THREAD

**Issue by elderling** [Chysn/wAx#1]
Please add build dependencies and instructions to make it easier for people who would like to build wAx from source.

**Comment by Chysn** [comment]
There are no dependencies. Just assemble /src/wax4k.asm. The source is written for the XA assembler, so the command to assemble is something like:

xa -o wax4k.bin wax4k.asm

If you want to create a file that can be loaded on a VIC-20, you'll need to have the two-byte header at the beginning. This can be added with the following command (Linux and macOS):

printf "\x00\x60" | cat - wax4k.bin > wax4k.prg

Hope this helps!

Regards,
Jason

**Comment by elderling** [comment]
Would you be willing to take your response to this issue and add it to the repository in some way? Maybe a README? I also noticed that there are more utilities in the "build" script than just xa, such as c1541 and petcat.

**Comment by Chysn** [comment]
The only thing really necessary to build wAx is the xa assembly, above. Everything else in the build script is for providing additional support formats. For example, petcat and c1541 (both included with VICE) are used to move things to the .d64 image. The 2716 and 2732 directories are for ROM images for cartridges.

**Comment by Chysn** [comment]
https://github.com/Chysn/wAx/wiki#assembling-wax

**Comment by elderling** [comment]
Thank you!
